name: build

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      GOLANGCI_LINT_VERSION: v1.38.0

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go
    - name: Check out code
      uses: actions/checkout@v2
    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time
    - name: Cache Go modules
      uses: actions/cache@v1
      id: cache-go-mod
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Cache bin directory
      id: cache-go-bin
      uses: actions/cache@v1
      with:
        path: ~/go/bin
        key: ${{ runner.os }}-go-bin-${{ env.GOLANGCI_LINT_VERSION }}
    - name: Install golangci-lint
      if: steps.cache-go-bin.outputs.cache-hit != 'true'
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $HOME/go/bin $GOLANGCI_LINT_VERSION
    - name: Lint
      run: $HOME/go/bin/golangci-lint run --timeout=2m ./...
    - name: Build kindly
      run: |
        mkdir ./dist/
        go build -ldflags='-s -w -X main.commit=${{ github.sha }} -X main.date=${{ steps.current-time.outputs.time }}' -o ./dist/ ./...